#Arquivo de configuração para CI/CD - Travis CI
#A tag matrix é utilizado para que seja configurado multiplo build/deploy - ANDROID/IOS

matrix:
  include:
    - os: linux
      language: android
      dist: trusty
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'

      # ANDROID BUILD
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28
          - sys-img-armeabi-v7a-google_apis-28
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-android-support
      jdk: oraclejdk8
      sudo: true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            - fonts-droid

      # HABILITAR LICENÇA ANDROID GRADLEW
      before_script:
        - yes | sdkmanager --update
        - ls -la
        - chmod +x android/gradlew #Dê permissão ao diretorio gradlew que apresenta no log do travis ci
      script:
        # EXECUTA SCRIPT PARA BUILD DO APPBUNDLE RELEASE
        - flutter build appbundle --release
        - gem install bundler && cd android && bundle install && cd ..
        - cd android
        # EXECUTA LANE PARA DEPLOY NO GOOGLE PLAY
        - bundle exec fastlane beta
        - ./gradlew assembleDebug
install:
  # INSTALA SDK FLUTTER - V2.17
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH="$PATH:`pwd`/flutter/bin"
before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/
 - $HOME/.pub-cache