# CONFIGURAÇÂO DO FASTLANE PARA DEPLOY NO GOOGLE PLAY
# update_fastlane

default_platform(:android)

platform :android do
  #desc "TESTANDO"
  #lane :test do
  #  gradle(task: "test")
  #end

  desc "ENVIANDO VERSAO BETA - GOOGLE PLAY"
  lane :beta do
    gradle(task:'assemble', build_type:'Release')
  end

  desc "DEPLOY NOVA VERSAO - GOOGLE PLAY"
  lane :playstore do
    gradle(
      task:'assemble',
      build_type:'Release'
    )
    upload_to_play_store(track:'production')
  end
end
