# CONFIGURAÇÂO DO FASTLANE PARA DEPLOY NO GOOGLE PLAY
# update_fastlane

default_platform(:android)

platform :android do
  desc "ENVIANDO VERSAO BETA - GOOGLE PLAY"
  lane :beta do
    gradle(task: 'assemble', build_type: 'Release')
    upload_to_play_store(track: 'beta')
    slack(message: 'Successfully distributed a new beta build')
  end

  desc "DEPLOY NOVA VERSAO - GOOGLE PLAY"
  lane :playstore do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    upload_to_play_store
  end
end
